development:
  adapter: mysql
  database: moxieforum_standalone_development
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  database: moxieforum_standalone_production
  username: root
  password:
  host: localhost
  
