production:
  adapter: mysql
  database: moxieforum_standalone_production
  username: root
  password:
  host: localhost

development:
  adapter: mysql
  database: moxieforum_standalone_development
  username: root
  password:
  host: localhost
  
test:
  adapter: mysql
  database: moxieforum_standalone_test
  username: root
  password:
  host: localhost
